"""Agent subsystem for Finch.ai: multi-turn execution loop, tool schemas, and 3-state permission engine."""
from .permissions import ToolPermissionMode, ToolPermissionEngine, resolve_tool_permission_mode
from .tools import (
    AGENT_ACTION_TOOLS,
    AGENT_TOOLS,
    ALL_AGENT_TOOLS,
    CHAT_TOOLS,
    FETCH_WEB_PAGE_TOOL,
    LIST_DIRECTORY_TOOL,
    LOAD_SESSION_TRANSCRIPT_TOOL,
    MEMORY_FACT_TOOLS,
    PYTHON_INTERPRETER_TOOL,
    READ_FILE_TOOL,
    RUN_TERMINAL_COMMAND_TOOL,
    SAVE_USER_FACT_TOOL,
    LIST_USER_FACTS_TOOL,
    SEARCH_PAST_CONVERSATIONS_TOOL,
    TOOL_CATEGORIES,
    TOOL_NAME_TO_CATEGORY,
    WEB_SEARCH_TOOL,
    WEB_TOOLS,
    WRITE_FILE_TOOL,
    ToolDispatcher,
)
from .loop import AgentLoop, AgentLoopResult

__all__ = [
    "ToolPermissionMode",
    "ToolPermissionEngine",
    "resolve_tool_permission_mode",
    "AgentLoop",
    "AgentLoopResult",
    "ToolDispatcher",
    "AGENT_ACTION_TOOLS",
    "AGENT_TOOLS",
    "ALL_AGENT_TOOLS",
    "CHAT_TOOLS",
    "FETCH_WEB_PAGE_TOOL",
    "LIST_DIRECTORY_TOOL",
    "LOAD_SESSION_TRANSCRIPT_TOOL",
    "MEMORY_FACT_TOOLS",
    "PYTHON_INTERPRETER_TOOL",
    "READ_FILE_TOOL",
    "RUN_TERMINAL_COMMAND_TOOL",
    "SAVE_USER_FACT_TOOL",
    "LIST_USER_FACTS_TOOL",
    "SEARCH_PAST_CONVERSATIONS_TOOL",
    "TOOL_CATEGORIES",
    "TOOL_NAME_TO_CATEGORY",
    "WEB_SEARCH_TOOL",
    "WEB_TOOLS",
    "WRITE_FILE_TOOL",
]
